import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');

const APP_SHELL_ROOT_FILES = [
    'index.html',
    'manifest.json',
    'assets/app.css',
    'assets/backtest.worker.js',
    'assets/strategy.worker.js'
];

const APP_SHELL_DIRS = ['assets/modules', 'assets/styles', 'assets/vendor', 'assets/icons'];

const DATA_FILES = ['data/pension720_stats.json', 'data/winning_stats.json'];

const EXCLUDE_FILES = new Set(['assets/sw-precache-manifest.js', 'online-check.txt']);

const INCLUDED_EXTENSIONS = new Set(['.js', '.css', '.woff', '.woff2', '.ttf', '.svg', '.png', '.json', '.html']);
const TEXT_HASH_EXTENSIONS = new Set(['.js', '.css', '.svg', '.json', '.html']);
const LEGACY_FONT_FALLBACK_EXTENSIONS = new Set(['.woff', '.ttf', '.svg']);

function shouldIncludeFile(relativePath) {
    const normalized = relativePath.replace(/\\/g, '/');
    const ext = path.extname(normalized).toLowerCase();
    if (!INCLUDED_EXTENSIONS.has(ext)) return false;
    if (EXCLUDE_FILES.has(normalized)) return false;
    if (normalized.startsWith('assets/vendor/phosphor/') && LEGACY_FONT_FALLBACK_EXTENSIONS.has(ext)) {
        return false;
    }
    return true;
}

function toManifestPath(relativePath = '') {
    const normalized = String(relativePath || '').replace(/\\/g, '/');
    return normalized === '' ? './' : `./${normalized}`;
}

async function walkDir(relativeDir) {
    const dirPath = path.resolve(repoRoot, relativeDir);
    const entries = await fs.readdir(dirPath, { withFileTypes: true });
    const files = [];

    for (const entry of entries) {
        const nextRelative = path.posix.join(relativeDir.replace(/\\/g, '/'), entry.name);
        if (entry.isDirectory()) {
            files.push(...(await walkDir(nextRelative)));
            continue;
        }

        if (!shouldIncludeFile(nextRelative)) continue;
        files.push(nextRelative);
    }

    return files;
}

async function buildPrecacheManifest() {
    const appShell = new Set(['./']);

    for (const file of APP_SHELL_ROOT_FILES) {
        if (!EXCLUDE_FILES.has(file)) appShell.add(toManifestPath(file));
    }

    for (const dir of APP_SHELL_DIRS) {
        const files = await walkDir(dir);
        files.forEach((file) => appShell.add(toManifestPath(file)));
    }

    const data = DATA_FILES.filter((file) => !EXCLUDE_FILES.has(file)).map((file) => toManifestPath(file));

    const manifest = {
        appShell: [...appShell].sort(),
        data: [...new Set(data)].sort()
    };
    manifest.version = await createPrecacheManifestVersion(manifest);
    return manifest;
}

async function createPrecacheManifestVersion(manifest) {
    const hash = createHash('sha256');
    const entries = [...(manifest.appShell || []), ...(manifest.data || [])].sort();

    for (const entry of entries) {
        hash.update(`${entry}\0`);
        if (entry === './') continue;
        const relativePath = entry.replace(/^\.\//, '');
        const filePath = path.resolve(repoRoot, relativePath);
        const buffer = await fs.readFile(filePath);
        const ext = path.extname(relativePath).toLowerCase();
        hash.update(
            TEXT_HASH_EXTENSIONS.has(ext) ? Buffer.from(buffer.toString('utf8').replace(/\r\n/g, '\n')) : buffer
        );
        hash.update('\0');
    }

    return `sha256-${hash.digest('hex').slice(0, 16)}`;
}

function renderManifestSource(manifest) {
    return `/* generated by scripts/generate_sw_manifest.mjs; do not edit by hand */\nself.__SW_PRECACHE_MANIFEST = Object.freeze(${JSON.stringify(manifest, null, 4)});\n`;
}

async function writeManifestFile() {
    const manifest = await buildPrecacheManifest();
    const outputPath = path.resolve(repoRoot, 'assets', 'sw-precache-manifest.js');
    await fs.writeFile(outputPath, renderManifestSource(manifest), 'utf8');
    return { manifest, outputPath };
}

if (process.argv[1] && path.resolve(process.argv[1]).toLowerCase() === __filename.toLowerCase()) {
    const { outputPath, manifest } = await writeManifestFile();
    console.log(
        JSON.stringify(
            {
                outputPath: path.relative(repoRoot, outputPath).replace(/\\/g, '/'),
                appShellCount: manifest.appShell.length,
                dataCount: manifest.data.length
            },
            null,
            2
        )
    );
}

export { buildPrecacheManifest, createPrecacheManifestVersion, renderManifestSource, writeManifestFile };
