const regressionExecutionPlan = [
    { name: 'runStrictFilterRegression', label: 'strict-filter regression', argKey: 'stats180' },
    { name: 'runWheelFixedNumbersRegression', label: 'wheel-fixed regression', argKey: 'stats180' },
    { name: 'runAdaptiveRecommendationDiagnosticsRegression', label: 'adaptive recommendation diagnostics regression', argKey: 'stats180' },
    { name: 'runDrawNormalizationRegression', label: 'draw-normalization regression' },
    { name: 'runFacadeExportParityRegression', label: 'facade export parity regression' },
    { name: 'runCampaignLimitRegression', label: 'campaign-limit regression' },
    { name: 'runCampaignCascadeRegression', label: 'campaign-cascade regression' },
    { name: 'runGeneratorStrategySelectionRegression', label: 'generator strategy-selection regression', awaited: true },
    { name: 'runCampaignDerivedSeedRegression', label: 'campaign derived-seed regression', argKey: 'stats180' },
    { name: 'runQrValidationRegression', label: 'qr-validation regression' },
    { name: 'runTicketDedupeRegression', label: 'ticket-dedupe regression' },
    { name: 'runTicketQuantityGroupingRegression', label: 'ticket-quantity grouping regression' },
    { name: 'runImmediateTicketSettlementRegression', label: 'immediate ticket settlement regression' },
    { name: 'runTicketReconcileRegression', label: 'ticket-reconcile regression', awaited: true },
    { name: 'runCampaignResetAutofillRecoveryRegression', label: 'campaign reset autofill recovery regression' },
    { name: 'runOrphanCampaignAutoCleanupRegression', label: 'orphan-campaign auto-cleanup regression' },
    { name: 'runCheckTargetDrawRegression', label: 'check-target-draw regression' },
    { name: 'runStoredListNormalizationRegression', label: 'stored-list-normalization regression' },
    { name: 'runLocalUpdatesFutureGuardRegression', label: 'future local-updates guard regression' },
    { name: 'runGeneratedTicketProvenanceRegression', label: 'generated ticket provenance regression' },
    { name: 'runHistoryActualLogRegression', label: 'history actual-log regression', awaited: true },
    { name: 'runClearLocalUpdatesReconcileRegression', label: 'clear-local-updates reconcile regression', awaited: true },
    { name: 'runTargetDrawAutofillRegression', label: 'target-draw autofill regression' },
    { name: 'runLatestWinPlaceholderRegression', label: 'latest-win-placeholder regression' },
    { name: 'runStrategyPresetCrudRegression', label: 'strategy-preset-crud regression' },
    { name: 'runSyncGuardRegression', label: 'sync-guard regression', awaited: true },
    { name: 'runRequestNumbersRegression', label: 'requestNumbers replace regression', awaited: true },
    { name: 'runRefreshCurrentRouteStaleRegression', label: 'refreshCurrentRoute stale regression', awaited: true },
    { name: 'runSyncLatestWinRefreshRegression', label: 'sync-latest-win refresh regression', awaited: true },
    { name: 'runWinningStatsLoadClassificationRegression', label: 'winning-stats load classification regression', awaited: true },
    { name: 'runPartialWinningStatsRecoveryRegression', label: 'partial winning-stats recovery regression', awaited: true },
    { name: 'runLocalRestoreSyncMetaRegression', label: 'local-restore sync-meta regression', awaited: true },
    { name: 'runRouteDataGateRegression', label: 'route data-gate regression' },
    { name: 'runSyncInvalidPayloadRegression', label: 'sync invalid payload regression', awaited: true },
    { name: 'runBuiltInSyncProviderRegression', label: 'built-in sync provider regression' },
    { name: 'runImportAlertOptionRegression', label: 'import-alert-options regression', awaited: true },
    { name: 'runImportOrphanCampaignCleanupRegression', label: 'import orphan-campaign cleanup regression', awaited: true },
    { name: 'runCampaignEmptySaveRegression', label: 'campaign-empty-save regression', awaited: true },
    { name: 'runQrScanReentryGuardRegression', label: 'qr-reentry-guard regression', awaited: true },
    { name: 'runQrRouteCleanupRegression', label: 'qr route cleanup regression', awaited: true },
    { name: 'runPostImportRefreshRegression', label: 'post-import-refresh regression', awaited: true },
    { name: 'runRuntimeAssetLocalizationRegression', label: 'runtime-asset-localization regression', awaited: true },
    { name: 'runAutoSyncFallbackRegression', label: 'auto-sync fallback regression', awaited: true },
    { name: 'runOfflineProbeRecoveryRegression', label: 'offline-probe recovery regression', awaited: true },
    { name: 'runBackgroundAutoSyncRegression', label: 'background auto-sync regression', awaited: true },
    { name: 'runPersistenceFlushRegression', label: 'persistence-flush regression' },
    { name: 'runNotificationPermissionRegression', label: 'notification-permission regression', awaited: true },
    { name: 'runRegressionBarrelExportParityRegression', label: 'regression barrel export parity regression', awaited: true },
    { name: 'runDataListPaginationRegression', label: 'data-list pagination regression' },
    { name: 'runDataListDomRegression', label: 'data-list DOM regression' },
    { name: 'runProxyPolicyRegression', label: 'proxy-policy regression' },
    { name: 'runProxyChangeAbortRegression', label: 'proxy-change abort regression', awaited: true },
    { name: 'runServiceWorkerReloadPolicyRegression', label: 'service-worker reload policy regression', awaited: true },
    { name: 'runServiceWorkerCoreDataPrecacheRegression', label: 'service-worker core data precache regression', awaited: true },
    { name: 'runHiddenAttributeStyleRegression', label: 'hidden-attribute style regression', awaited: true },
    { name: 'runLocalFontPathRegression', label: 'local font path regression', awaited: true },
    { name: 'runRecommendationCopyRegression', label: 'recommendation copy regression', awaited: true },
    { name: 'runRecommendationRuntimePolicyRegression', label: 'recommendation runtime policy regression', awaited: true }
];

const regressionBarrelExportNames = [
    'runBacktestSmoke',
    'runBackupSmoke',
    ...regressionExecutionPlan.map(({ name }) => name)
];

export {
    regressionBarrelExportNames,
    regressionExecutionPlan
};
